// src/init/render.ts — Render InitAnswers into a yaml config string.
// Pure function so it's trivially testable without spinning up ink.

import type { InitAnswers } from "./wizard.js";

const HEADER = `# ~/.isotopes/isotopes.yaml
# Generated by \`isotopes init\`. See isotopes.example.yaml in the repo
# (https://github.com/GhostComplex/isotopes) for the full set of options.
`;

const PROVIDER_SKIP = `# provider:
#   type: anthropic
#   model: claude-sonnet-4-5-20250929
#   apiKey: \${ANTHROPIC_API_KEY}
`;

function renderProvider(answers: InitAnswers): string {
  if (answers.llm !== "ghc-proxy" || !answers.ghcProxy) return PROVIDER_SKIP;
  const { baseUrl, apiKey, model } = answers.ghcProxy;
  return `provider:
  type: anthropic-proxy
  baseUrl: ${baseUrl}
  apiKey: ${apiKey}
  model: ${model}
`;
}

const TOOLS = `tools:
  cli: false                # Shell execution (turn on once you trust the agent)
  fs:
    workspaceOnly: true     # File tools restricted to the agent's workspace
`;

const AGENTS = `agents:
  - id: assistant
    name: Assistant
    systemPrompt: |
      You are a helpful assistant running locally via Isotopes.
`;

function renderChannels(answers: InitAnswers): string {
  if (answers.channel !== "discord" || !answers.discord) return "";
  const { token } = answers.discord;
  return `
channels:
  discord:
    accounts:
      main:
        token: ${token}
        defaultAgentId: assistant
        dm:
          policy: disabled
        threadBindings:
          enabled: true
`;
}

export function renderConfig(answers: InitAnswers): string {
  return [HEADER, renderProvider(answers), TOOLS, AGENTS, renderChannels(answers)]
    .filter((s) => s.length > 0)
    .join("\n");
}
